# Generated by Django 4.2.9 on 2024-05-23 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Ingredient', models.IntegerField(default=0)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=255)),
                ('possible_units', models.CharField(blank=True, default='', null=True)),
                ('estimated_cost_value', models.FloatField(blank=True, default=0)),
                ('estimated_cost_unit', models.CharField(blank=True, default='', max_length=255)),
                ('consistency', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('shopping_list_units', models.TextField(blank=True, default='', null=True)),
                ('img', models.ImageField(blank=True, default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientID',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('id_ingredients', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default=0, max_length=255)),
                ('is_plant_binary', models.BooleanField(default=True)),
                ('is_plant_probability', models.FloatField(default=1)),
                ('image', models.ImageField(default=None, upload_to='images/')),
                ('latitude', models.FloatField(blank=True, default=0)),
                ('longitude', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeightPerServing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planta.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recepy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_recepy', models.IntegerField(blank=True, default=0)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', models.URLField(blank=True)),
                ('used_ingredient_count', models.IntegerField(blank=True)),
                ('missed_ingredient_count', models.IntegerField(blank=True)),
                ('ingredient', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='planta.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planta.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Plant_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.FloatField(default=0)),
                ('name', models.CharField(default=0, max_length=255)),
                ('common_names', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default=None)),
                ('taxonomy', models.TextField(blank=True, default='')),
                ('gbif_id', models.IntegerField(blank=True, default=0)),
                ('inaturalist_id', models.IntegerField(blank=True, default='')),
                ('image', models.URLField(blank=True, default=None)),
                ('edible_parts', models.TextField(blank=True, default='')),
                ('propagation_methods', models.TextField(blank=True, default='')),
                ('watering_min', models.IntegerField(blank=True, default=0)),
                ('watering_max', models.IntegerField(blank=True, default=0)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planta.plant')),
            ],
        ),
        migrations.CreateModel(
            name='NutrientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('unit', models.CharField(blank=True, default='', max_length=255)),
                ('percent_of_daily_needs', models.FloatField(blank=True, default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planta.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientRecepy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ingredientrecepy', models.IntegerField()),
                ('amount', models.FloatField(blank=True)),
                ('unit', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('meta', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('is_missed', models.BooleanField(blank=True, default=False)),
                ('recepy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planta.recepy')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='plant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planta.plant_data'),
        ),
        migrations.CreateModel(
            name='HealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_healthy_binary', models.BooleanField(default=True)),
                ('is_healthy_probability', models.FloatField(default=1)),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planta.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Flavonoid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('unit', models.CharField(blank=True, default='', max_length=255)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planta.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='DiseaseSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_DiseaseSuggestion', models.CharField(blank=True, default='')),
                ('name', models.CharField(blank=True, default='')),
                ('probability', models.FloatField(blank=True, default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(blank=True, default=None)),
                ('treatment_chemical', models.CharField(blank=True, null=True)),
                ('treatment_biological', models.CharField(blank=True, null=True)),
                ('prevention', models.CharField(blank=True, default=dict, null=True)),
                ('common_names_disease', models.CharField(blank=True, default='', null=True)),
                ('cause', models.CharField(blank=True, default='', null=True)),
                ('health_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planta.healthassessment')),
            ],
        ),
        migrations.CreateModel(
            name='CaloricBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_protein', models.FloatField(blank=True, default=0)),
                ('percent_fat', models.FloatField(blank=True, default=0)),
                ('percent_carbs', models.FloatField(blank=True, default=0)),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='planta.ingredient')),
            ],
        ),
    ]
