# Generated by Django 4.2.9 on 2024-05-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='plant',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='plant',
            field=models.ManyToManyField(to='planta.plant_data'),
        ),
    ]
