# Generated by Django 4.2.9 on 2024-05-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0002_remove_ingredient_plant_ingredient_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flavonoid',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='nutrientdetail',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='property',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='flavonoid',
            name='ingredient',
            field=models.ManyToManyField(to='planta.ingredient'),
        ),
        migrations.AddField(
            model_name='nutrientdetail',
            name='ingredient',
            field=models.ManyToManyField(to='planta.ingredient'),
        ),
        migrations.AddField(
            model_name='property',
            name='ingredient',
            field=models.ManyToManyField(to='planta.ingredient'),
        ),
    ]
