# Generated by Django 4.2.9 on 2024-05-25 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0003_remove_flavonoid_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caloricbreakdown',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planta.ingredient'),
        ),
        migrations.RemoveField(
            model_name='flavonoid',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='nutrientdetail',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='property',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='weightperserving',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planta.ingredient'),
        ),
        migrations.AddField(
            model_name='flavonoid',
            name='ingredient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='planta.ingredient'),
        ),
        migrations.AddField(
            model_name='nutrientdetail',
            name='ingredient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='planta.ingredient'),
        ),
        migrations.AddField(
            model_name='property',
            name='ingredient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='planta.ingredient'),
        ),
    ]
