# Generated by Django 4.2.9 on 2024-05-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0005_remove_ingredient_plant_ingredient_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='plant',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='plant',
            field=models.ManyToManyField(to='planta.plant_data'),
        ),
    ]
