# Generated by Django 4.2.9 on 2024-05-25 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0006_remove_ingredient_plant_ingredient_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='plant',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='plant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='planta.plant_data'),
        ),
    ]
