# Generated by Django 4.2.9 on 2024-05-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0007_remove_ingredient_plant_ingredient_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='shopping_list_units',
        ),
    ]
