# Generated by Django 4.2.9 on 2024-05-25 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0008_remove_ingredient_shopping_list_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='access_token',
            new_name='plant_access_token',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='image',
            new_name='plant_image',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='is_plant_binary',
            new_name='plant_is_plant_binary',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='is_plant_probability',
            new_name='plant_is_plant_probability',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='latitude',
            new_name='plant_latitude',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='longitude',
            new_name='plant_longitude',
        ),
    ]
