# Generated by Django 4.2.9 on 2024-05-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0009_rename_access_token_plant_plant_access_token_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant_data',
            old_name='common_names',
            new_name='plant_data_common_names',
        ),
        migrations.RenameField(
            model_name='plant_data',
            old_name='edible_parts',
            new_name='plant_data_edible_parts',
        ),
        migrations.RenameField(
            model_name='plant_data',
            old_name='gbif_id',
            new_name='plant_data_gbif_id',
        ),
        migrations.RenameField(
            model_name='plant_data',
            old_name='image',
            new_name='plant_data_image',
        ),
        migrations.RenameField(
            model_name='plant_data',
            old_name='inaturalist_id',
            new_name='plant_data_inaturalist_id',
        ),
        migrations.RenameField(
            model_name='plant_data',
            old_name='name',
            new_name='plant_data_name',
        ),
        migrations.RenameField(
            model_name='plant_data',
            old_name='plant',
            new_name='plant_data_plant',
        ),
        migrations.RenameField(
            model_name='plant_data',
            old_name='probability',
            new_name='plant_data_probability',
        ),
        migrations.RenameField(
            model_name='plant_data',
            old_name='propagation_methods',
            new_name='plant_data_propagation_methods',
        ),
        migrations.RenameField(
            model_name='plant_data',
            old_name='taxonomy',
            new_name='plant_data_taxonomy',
        ),
        migrations.RenameField(
            model_name='plant_data',
            old_name='url',
            new_name='plant_data_url',
        ),
        migrations.RenameField(
            model_name='plant_data',
            old_name='watering_max',
            new_name='plant_data_watering_max',
        ),
        migrations.RenameField(
            model_name='plant_data',
            old_name='watering_min',
            new_name='plant_data_watering_min',
        ),
    ]
