# Generated by Django 4.2.9 on 2024-05-25 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0010_rename_common_names_plant_data_plant_data_common_names_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthassessment',
            old_name='is_healthy_binary',
            new_name='health_is_healthy_binary',
        ),
        migrations.RenameField(
            model_name='healthassessment',
            old_name='is_healthy_probability',
            new_name='health_is_healthy_probability',
        ),
        migrations.RenameField(
            model_name='healthassessment',
            old_name='plant',
            new_name='health_plant',
        ),
    ]
