# Generated by Django 4.2.9 on 2024-05-25 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0011_rename_is_healthy_binary_healthassessment_health_is_healthy_binary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasesuggestion',
            old_name='cause',
            new_name='disease_cause',
        ),
        migrations.RenameField(
            model_name='diseasesuggestion',
            old_name='common_names_disease',
            new_name='disease_common_names_disease',
        ),
        migrations.RenameField(
            model_name='diseasesuggestion',
            old_name='description',
            new_name='disease_description',
        ),
        migrations.RenameField(
            model_name='diseasesuggestion',
            old_name='health_assessment',
            new_name='disease_health_assessment',
        ),
        migrations.RenameField(
            model_name='diseasesuggestion',
            old_name='id_DiseaseSuggestion',
            new_name='disease_id_DiseaseSuggestion',
        ),
        migrations.RenameField(
            model_name='diseasesuggestion',
            old_name='name',
            new_name='disease_name',
        ),
        migrations.RenameField(
            model_name='diseasesuggestion',
            old_name='prevention',
            new_name='disease_prevention',
        ),
        migrations.RenameField(
            model_name='diseasesuggestion',
            old_name='probability',
            new_name='disease_probability',
        ),
        migrations.RenameField(
            model_name='diseasesuggestion',
            old_name='treatment_biological',
            new_name='disease_treatment_biological',
        ),
        migrations.RenameField(
            model_name='diseasesuggestion',
            old_name='treatment_chemical',
            new_name='disease_treatment_chemical',
        ),
        migrations.RenameField(
            model_name='diseasesuggestion',
            old_name='url',
            new_name='disease_url',
        ),
    ]
