# Generated by Django 4.2.9 on 2024-05-25 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0012_rename_cause_diseasesuggestion_disease_cause_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientid',
            old_name='id_ingredients',
            new_name='spoon_id_ingredients',
        ),
        migrations.RenameField(
            model_name='ingredientid',
            old_name='name',
            new_name='spoon_name',
        ),
    ]
