# Generated by Django 4.2.9 on 2024-05-25 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0013_rename_id_ingredients_ingredientid_spoon_id_ingredients_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='amount',
            new_name='ingredient_amount',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='consistency',
            new_name='ingredient_consistency',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='estimated_cost_unit',
            new_name='ingredient_estimated_cost_unit',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='estimated_cost_value',
            new_name='ingredient_estimated_cost_value',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='id_Ingredient',
            new_name='ingredient_id_Ingredient',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='img',
            new_name='ingredient_img',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='original_name',
            new_name='ingredient_original_name',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='plant',
            new_name='ingredient_plant',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='possible_units',
            new_name='ingredient_possible_units',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='ingredient_unit',
        ),
    ]
