# Generated by Django 4.2.9 on 2024-05-25 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0014_rename_amount_ingredient_ingredient_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flavonoid',
            old_name='amount',
            new_name='flavonoid_amount',
        ),
        migrations.RenameField(
            model_name='flavonoid',
            old_name='ingredient',
            new_name='flavonoid_ingredient',
        ),
        migrations.RenameField(
            model_name='flavonoid',
            old_name='name',
            new_name='flavonoid_name',
        ),
        migrations.RenameField(
            model_name='flavonoid',
            old_name='unit',
            new_name='flavonoid_unit',
        ),
        migrations.RenameField(
            model_name='nutrientdetail',
            old_name='amount',
            new_name='nutrient_amount',
        ),
        migrations.RenameField(
            model_name='nutrientdetail',
            old_name='ingredient',
            new_name='nutrient_ingredient',
        ),
        migrations.RenameField(
            model_name='nutrientdetail',
            old_name='name',
            new_name='nutrient_name',
        ),
        migrations.RenameField(
            model_name='nutrientdetail',
            old_name='percent_of_daily_needs',
            new_name='nutrient_percent_of_daily_needs',
        ),
        migrations.RenameField(
            model_name='nutrientdetail',
            old_name='unit',
            new_name='nutrient_unit',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='amount',
            new_name='property_amount',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='ingredient',
            new_name='property_ingredient',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='name',
            new_name='property_name',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='unit',
            new_name='property_unit',
        ),
    ]
