# Generated by Django 4.2.9 on 2024-05-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0015_rename_amount_flavonoid_flavonoid_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caloricbreakdown',
            old_name='ingredient',
            new_name='cb_ingredient',
        ),
        migrations.RenameField(
            model_name='caloricbreakdown',
            old_name='percent_carbs',
            new_name='cb_percent_carbs',
        ),
        migrations.RenameField(
            model_name='caloricbreakdown',
            old_name='percent_fat',
            new_name='cb_percent_fat',
        ),
        migrations.RenameField(
            model_name='caloricbreakdown',
            old_name='percent_protein',
            new_name='cb_percent_protein',
        ),
        migrations.RenameField(
            model_name='weightperserving',
            old_name='amount',
            new_name='wps_amount',
        ),
        migrations.RenameField(
            model_name='weightperserving',
            old_name='ingredient',
            new_name='wps_ingredient',
        ),
        migrations.RenameField(
            model_name='weightperserving',
            old_name='unit',
            new_name='wps_unit',
        ),
    ]
