# Generated by Django 4.2.9 on 2024-05-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0016_rename_ingredient_caloricbreakdown_cb_ingredient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recepy',
            old_name='id_recepy',
            new_name='recepy_id_recepy',
        ),
        migrations.RenameField(
            model_name='recepy',
            old_name='image',
            new_name='recepy_image',
        ),
        migrations.RenameField(
            model_name='recepy',
            old_name='ingredient',
            new_name='recepy_ingredient',
        ),
        migrations.RenameField(
            model_name='recepy',
            old_name='missed_ingredient_count',
            new_name='recepy_missed_ingredient_count',
        ),
        migrations.RenameField(
            model_name='recepy',
            old_name='title',
            new_name='recepy_title',
        ),
        migrations.RenameField(
            model_name='recepy',
            old_name='used_ingredient_count',
            new_name='recepy_used_ingredient_count',
        ),
    ]
