# Generated by Django 4.2.9 on 2024-05-28 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0018_rename_amount_ingredientrecepy_ingrecepy_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant_data',
            old_name='plant_data_common_names',
            new_name='pd_common_names',
        ),
    ]
