# Generated by Django 4.2.9 on 2024-05-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0019_rename_plant_data_common_names_plant_data_pd_common_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant_data',
            old_name='pd_common_names',
            new_name='plant_data_common_names',
        ),
    ]
