# Generated by Django 4.2.9 on 2024-06-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planta', '0021_plant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='plant_latitude',
            field=models.FloatField(blank=True, default=4.787029680509281),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_longitude',
            field=models.FloatField(blank=True, default=-74.15851704555615),
        ),
    ]
